### ISSUE TITLE
I have a problem during training

### ISSUE THREAD

**Issue by RobinLiuZX** [twke18/HSG#2]
![question](https://user-images.githubusercontent.com/80163805/183562110-6cc890a7-1380-47d9-ba4a-5a934189f749.png)

I used a GPU card on the server to train with your open source code, and the result was stuck in this training progress. I strictly configured the environment you gave, using pytorch==1.12, python==3.7.9, may I ask you What are your thoughts on this issue?

**Comment by twke18** [comment]
If you are using a GPU card, have you tried to set GPUS=0 [here](https://github.com/twke18/HSG/blob/8de138f7d90ce4f87f29ca274e67f60e48ff09e2/bashscripts/coco/train.sh#L21)?

Also, have you checked the occupancy of GPU memory? It's also likely that OOM occurred and the process halted.

**Comment by RobinLiuZX** [comment]
Thank you for your reply. My GPU memory is NVIDIA-A100 with 40960MB. Running according to the batch size of 16 you set, it only takes up 9683 memory, and I set the GPU ID to 0.

**Comment by RobinLiuZX** [comment]
Thank you for your reply. My GPU memory is NVIDIA-A100 with 40960MB. Running according to the batch size of 16 you set, it only takes up 9683 memory, and I set the GPU ID to 0.

**Comment by RobinLiuZX** [comment]
Thank you for your reply. My GPU memory is NVIDIA-A100 with 40960MB. Running according to the batch size of 16 you set, it only takes up memory of 9683MB, and I set the GPU ID to 0.

**Comment by RobinLiuZX** [comment]
Thank you for your reply. My GPU memory is NVIDIA-A100 with 40960MB. Running according to the batch size of 16 you set, it only takes up memory of 9683MB, and I set the GPUS=0.

**Comment by Lan-MC** [comment]
encounter the same problem...

**Comment by twke18** [comment]
@RobinLiuZX , do you still have the problem?

@Lan-MC , are you also using a single GPU for training?

**Comment by Lan-MC** [comment]
> 

I use 2 GPUs for training.
