### ISSUE TITLE
comparison with SOTA

### ISSUE THREAD

**Issue by eliabruni** [twke18/HSG#3]
Hi, great work! 

However, I am little confused about your comparison against SOTA methods. For instance, wrt cityscapes, why don't you compare against STEGO? Is it because you are computing scores on cityscapes val set while STEGO on test set? If yes, would you then compare against this method: https://paperswithcode.com/sota/unsupervised-semantic-segmentation-on-1? Also, do you have results on cityscapes test set? 

Thanks.

**Comment by twke18** [comment]
We submitted our HSG (CVPR 2022, November 2021) before STEGO was put on the arxiv (March 2022).

To compare with these methods on Cityscapes, you can use our code and released model to perform inference on the test set.
