### ISSUE TITLE
Do you know how to train the original Segsort to compare?

### ISSUE THREAD

**Issue by J-JunChen** [twke18/HSG#4]
Hello! Thanks for your job.

I would like to know how to train the original Segsort to compare with your method. Because the original source code of Segsort was basing on Tensorflow, did you reproduced the Segsort on Pytorch for comparsion?

**Comment by twke18** [comment]
You can set every loss_type [here](https://github.com/twke18/HSG/blob/8de138f7d90ce4f87f29ca274e67f60e48ff09e2/bashscripts/coco/train.sh#L42-L50) to `none`.

**Comment by J-JunChen** [comment]
> You can set every loss_type [here](https://github.com/twke18/HSG/blob/8de138f7d90ce4f87f29ca274e67f60e48ff09e2/bashscripts/coco/train.sh#L42-L50) to `none`.

Ok, I see. I have another question, do you know how to train and inference in VOC dataset? Because the Segsort claim that "we do not pre-train on any other segmentation dataset, such as MS COCO [44] dataset." for VOC.

**Comment by twke18** [comment]
In the original paper, SegSort indeed does not train on MSCOCO.  However, for fair comparison, we reproduce SegSort based on our experimental setting.

There are several difference:
 
1. We don't use ImageNet-trained backbone, but train all models from scratch.
2. We train all models on MSCOCO and test on VOC.

Hope these answer your question.

**Comment by J-JunChen** [comment]
Ok, Thanks.
