### ISSUE TITLE
There is a missing file issue

### ISSUE THREAD

**Issue by YMX-zknu** [twke18/HSG#7]
Hi author, the following error occurs when executing the `train.sh` file for the cityscapes dataset:
![image](https://github.com/twke18/HSG/assets/39787386/bcd681a6-2d1c-4838-8406-9d63eb5f9f41)

The `gtFineInstId` file is mentioned in the `datasets/cityscapes/val.txt` file (shown below), but it is not present in the Cityscapes dataset constructed according to your request, how can this be resolved?
![image](https://github.com/twke18/HSG/assets/39787386/dd197963-0208-4b5e-8bc4-d69c8c3cbfad)

**Comment by twke18** [comment]
Hi, the files are the ground-truth instance masks of Cityscapes.  They are not used for inference at all.  You can either replace them with some dummy files, or download from [here](https://github.com/twke18/HSG/blob/master/misc/gtFineInstId.zip).
